# Generated by Django 2.1.4 on 2019-01-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_user_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(max_length=100)),
                ('years_of_experience', models.CharField(max_length=2)),
                ('fee', models.CharField(max_length=5)),
                ('degree', models.CharField(max_length=200)),
                ('visit_days', models.CharField(max_length=200)),
                ('two_shift', models.CharField(max_length=10)),
                ('first_shift_start', models.CharField(max_length=10)),
                ('first_shift_end', models.CharField(max_length=10)),
                ('second_shift_start', models.CharField(max_length=10)),
                ('second_shift_end', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.DoctorInformation'),
        ),
    ]
