# Generated by Django 2.1.4 on 2019-01-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20190102_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinformation',
            name='degree',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='fee',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='first_shift_end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='first_shift_start',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='second_shift_end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='second_shift_start',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='specialisation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='two_shift',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='visit_days',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='years_of_experience',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
