# Generated by Django 2.1.4 on 2019-01-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20190102_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Insurance'),
        ),
    ]
